---
title: "R Notebook"
output: html_notebook
---

## Setup

```{r}
library(here)
library(tidyverse)
library(ggpubr)
library(extrafont)
library(cutr)
loadfonts()
rda_174_lfcs <- read_csv(here('data','interim',
                              'RDA_174_LFC.csv')) %>%
  separate(`Construct IDs`, c('Guide Sequence', 'Gene'), sep = ';')
essential_predictions <- read_tsv(here('data','external',
                                  'deepcpf1_hacked_essential_output.txt'))
eesential_tiers <- essential_predictions %>%
  mutate(Tier = ifelse(grepl('TTT(A|C|G)', PAM), 'TTTV', 'TTTT'))
eef2_predictions <- read_tsv(here('data','external',
                                  'deepcpf1_hacked_eef2_output.txt'))
eef2_tiers <- read_tsv(here('data','external','Tier_input_v2.txt')) %>%
  select(PAM, Tier) %>%
  mutate(Tier = ifelse(grepl('TTT(A|C|G)', PAM), 'TTTV', ifelse(PAM == 'TTTT', 'TTTT', Tier)), 
         Tier = fct_recode(Tier, 'none' = 'Tier 4'), 
         Tier = factor(Tier, levels = c('TTTT','TTTV', 'Tier 1', 'Tier 2', 'Tier 3', 'none'))) %>%
  mutate(`PAM 1-3 T Count` = as.factor(str_count(substr(PAM,1,3), 'T')))
```

```{r}
eef2_predictions_tiers <- inner_join(eef2_predictions, eef2_tiers) %>%
    mutate(sequence_type = word(sequence_type, 1, sep = '_'))
tttv_avg_predictions <- eef2_predictions_tiers %>%
  filter(sequence_type %in% c('TTTA', 'TTTC', 'TTTG')) %>%
  group_by_at(vars(`Context Sequence`:end_context, Tier)) %>%
  summarise(`Seq-DeepCpf1 Score` = mean(`Seq-DeepCpf1 Score`))%>%
  mutate(sequence_type = 'TTTV Avg.')
eef2_expanded_predictions <- bind_rows(eef2_predictions_tiers, tttv_avg_predictions)
```

```{r}
flow_controls <- c('CD81','ICAM1','FAS','CD33')
flow_lfcs <- rda_174_lfcs %>%
  filter(Gene %in% flow_controls) %>%
  mutate(avg_lfc = (`A375|RDA_174|no drug|NA|pDNA|A|LFC` + 
                      `A375|RDA_174|no drug|NA|pDNA|B|LFC`)/2)
flow_cutoff <- quantile(flow_lfcs$avg_lfc, 0.05)
eef2_binarized <- eef2_expanded_predictions %>%
  mutate(active = as.numeric(Avg_LFC < flow_cutoff))
eef2_tiers_percent_active = eef2_binarized %>%
  filter(sequence_type == 'Orig') %>%
  group_by(Tier) %>%
  summarise(n = n(),
    fraction_active = round(sum(active)/n, 2),
    active_label = paste0(fraction_active*100, '%'), 
    n_label = paste0('n=', n))

ggplot(eef2_binarized %>% filter(sequence_type == 'Orig')) +
  aes(x = Tier, y = Avg_LFC, fill = Tier, alpha = Tier) +
  geom_boxplot(show.legend = FALSE) +
  #geom_violin(show.legend = FALSE) +
  geom_label(size = 3, data = eef2_tiers_percent_active, aes(label = active_label, 
                                                   x = Tier, y = -6), show.legend = FALSE) +
  geom_label(size = 3, data = eef2_tiers_percent_active, aes(label = n_label, 
                                                   x = Tier, y = 2.5), show.legend = FALSE) +
  geom_hline(yintercept = flow_cutoff, linetype = 'dashed') +
  theme_classic() +
  theme(text = element_text(size = 10)) +
  ggtitle('enCas12a EEF2 Guides') +
  xlab('PAM') + 
  ylab('Avg. LFC') +
  scale_fill_manual(values = c('#4878d0','#4878d0', '#4878d0', '#ee854a', '#6acc64', 'darkgrey')) +
  scale_alpha_manual(values = c(0.2,0.5,1,1,1,1))
ggsave(here('figures','ML','alt','EEF2_guide_activity_1th.pdf'), width = 11, height = 9, units = 'cm', useDingbats = FALSE)
```


```{r}
essential_genes <- c('EEF2','PELP1','HNRPU','TFRC','SF3B1','PSMA6','LPNB1','SNRPD1','RPS20','POLR1C')
essential_tiers_active <- eesential_tiers %>% 
  filter(sequence_type == 'Orig_sequence', Gene %in% essential_genes) %>%
  mutate(active = Avg_LFC < flow_cutoff) %>%
  group_by(Tier) %>%
  summarise(n = n(),
            fraction_active = round(sum(active)/n, 2),
            active_label = paste0(fraction_active*100, '%'), 
            n_label = paste0('n=', n))
  
  
ggplot(eesential_tiers %>% filter(sequence_type == 'Orig_sequence', Gene %in% essential_genes)) +
  aes(x = Tier, y = Avg_LFC, fill = Tier) +
  geom_boxplot(show.legend = FALSE) +
  #geom_violin(show.legend = FALSE) +
  geom_label(size = 3, data = essential_tiers_active, aes(label = active_label, 
                                                   x = Tier, y = -6), show.legend = FALSE) +
  geom_label(size = 3, data = essential_tiers_active, aes(label = n_label, 
                                                   x = Tier, y = 2.5), show.legend = FALSE) +
  geom_hline(yintercept = flow_cutoff, linetype = 'dashed') +
  theme_classic() +
  theme(text = element_text(size = 10)) +
  ggtitle('enCas12a Essential Guides') +
  xlab('PAM') + 
  ylab('Avg. LFC') 
ggsave(here('figures','ML','alt','Essential_guide_activity.pdf'), width = 11, height = 9, units = 'cm', useDingbats = FALSE)

```







